
import { Client } from '@/types';
import { supabase } from '@/integrations/supabase/client';

// Initial clients data for demo purposes - will be used only if fetching fails
export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'Supermercado Nordeste LTDA',
    tradingName: 'Supermercado Nordeste',
    document: '12.345.678/0001-00',
    address: 'Av. Dom Luis, 500, Sala 302, Aldeota',
    street: 'Av. Dom Luis',
    number: '500',
    complement: 'Sala 302',
    neighborhood: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
    zipCode: '60160230',
    contact: 'Maria Silva',
    phone: '(85) 3322-1122',
    email: 'contato@supnordeste.com.br',
    priceTableId: 'table-a',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-2',
    name: 'Farmácia Popular Comércio de Medicamentos LTDA',
    tradingName: 'Farmácia Popular',
    document: '23.456.789/0001-11',
    address: 'Rua Padre Valdevino, 100, Joaquim Távora',
    street: 'Rua Padre Valdevino',
    number: '100',
    complement: '',
    neighborhood: 'Joaquim Távora',
    city: 'Fortaleza',
    state: 'CE',
    zipCode: '60135040',
    contact: 'Carlos Mendes',
    phone: '(85) 3433-5566',
    email: 'atendimento@farmaciapopular.com.br',
    priceTableId: 'table-b',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-3',
    name: 'Hospital São Camilo S.A.',
    tradingName: 'Hospital São Camilo',
    document: '34.567.890/0001-22',
    address: 'Av. Barão de Studart, 2000, Bloco A, Aldeota',
    street: 'Av. Barão de Studart',
    number: '2000',
    complement: 'Bloco A',
    neighborhood: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
    zipCode: '60120000',
    contact: 'Ana Beatriz',
    phone: '(85) 3288-9900',
    email: 'logistica@hospitalsaocamilo.com',
    priceTableId: 'table-c',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-4',
    name: 'Distribuidora Central Comércio e Serviços LTDA',
    tradingName: 'Distribuidora Central',
    document: '45.678.901/0001-33',
    address: 'Rodovia BR-116, Km 10, Galpão 5, Centro',
    street: 'Rodovia BR-116',
    number: 'Km 10',
    complement: 'Galpão 5',
    neighborhood: 'Centro',
    city: 'Eusébio',
    state: 'CE',
    zipCode: '61760000',
    contact: 'Paulo Roberto',
    phone: '(85) 3344-7788',
    email: 'paulo@distcentral.com.br',
    priceTableId: 'table-d',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Map Supabase client data to our Client type
export const mapSupabaseClientToClient = (client: any): Client => ({
  id: client.id,
  name: client.name,
  tradingName: client.trading_name || '',
  document: client.document || '',
  address: client.address || '',
  street: client.street || '',
  number: client.number || '',
  complement: client.complement || '',
  neighborhood: client.neighborhood || '',
  city: client.city || '',
  state: client.state || '',
  zipCode: client.zip_code || '',
  contact: client.contact || '',
  phone: client.phone || '',
  email: client.email || '',
  priceTableId: client.price_table_id || '',
  notes: client.notes || '',
  createdAt: client.created_at || new Date().toISOString(),
  updatedAt: client.updated_at || new Date().toISOString(),
});

// Map Client type to Supabase client data
export const mapClientToSupabaseClient = (
  client: Omit<Client, 'id' | 'createdAt' | 'updatedAt'>, 
  userId?: string
) => ({
  name: client.name,
  trading_name: client.tradingName,
  document: client.document,
  address: client.address,
  street: client.street,
  number: client.number,
  complement: client.complement,
  neighborhood: client.neighborhood,
  city: client.city,
  state: client.state,
  zip_code: client.zipCode,
  contact: client.contact,
  phone: client.phone,
  email: client.email,
  price_table_id: client.priceTableId,
  notes: client.notes,
  user_id: userId,
});
